package com.fieldops.user.mapper;

import com.fieldops.user.model.Role;
import com.fieldops.user.model.User;
import com.fieldops.user.dto.UserResponse;
import org.mapstruct.Mapper;

/**
 * Maps between the {@link User} entity and its {@link UserResponse} DTO.
 * Generated by MapStruct at compile time.
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    UserResponse toResponse(User user);

    UserResponse toResponse(Long id, String name, String email, Role role);
}
