package com.fieldops.user.mapper;

import com.fieldops.user.model.Perfil;
import com.fieldops.user.model.Usuario;
import com.fieldops.user.dto.UsuarioResponse;
import org.mapstruct.Mapper;

/**
 * Maps between the {@link Usuario} entity and its {@link UsuarioResponse} DTO.
 * Generated by MapStruct at compile time.
 */
@Mapper(componentModel = "spring")
public interface UsuarioMapper {

    UsuarioResponse toResponse(Usuario usuario);

    UsuarioResponse toResponse(Long id, String nome, String email, Perfil perfil);
}
