import { Copy, Eye, FileClock, Pencil, Plus } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { Badge } from '@/components/badges/Badge'
import { PageHeader } from '@/components/layout/PageHeader'
import { DataTable, type Column } from '@/components/tables/DataTable'
import { Button } from '@/components/ui/Button'
import { templates } from '@/mocks/domain'
import type { InspectionTemplate } from '@/types/domain'
export function TemplatesPage() { const navigate = useNavigate(); const columns: Column<InspectionTemplate>[] = [{ header: 'Titulo', cell: t => <span className="font-medium">{t.title}</span> }, { header: 'Categoria', cell: t => t.category }, { header: 'Versao atual', cell: t => `v${t.version}` }, { header: 'Secoes', cell: t => t.sections.length }, { header: 'Itens', cell: t => t.sections.reduce((sum, section) => sum + section.items.length, 0) }, { header: 'Status', cell: t => <Badge tone={t.status === 'Ativa' ? 'success' : 'warning'}>{t.status}</Badge> }, { header: 'Acoes', cell: t => <div className="flex flex-wrap gap-2"><Button variant="ghost" className="h-8 px-2" onClick={() => navigate(`/app/inspection-templates/${t.id}/edit`)}><Pencil size={16} />Editar</Button><Button variant="ghost" className="h-8 px-2" onClick={() => navigate(`/app/inspection-templates/${t.id}/preview`)}><Eye size={16} />Previa</Button><Button variant="ghost" className="h-8 px-2"><FileClock size={16} />Versoes</Button><Button variant="ghost" className="h-8 px-2"><Copy size={16} />Duplicar</Button></div> }]; return <div className="space-y-6"><PageHeader title="Modelos de inspecao" description="Crie e publique checklists utilizados pelos tecnicos." action={<Link to="/app/inspection-templates/tpl-compressor/edit"><Button><Plus size={17} />Novo modelo</Button></Link>} /><DataTable columns={columns} rows={templates} /></div> }
