import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';

import { Button, Card } from '@/design-system';
import { Colors, FontSize, FontWeight, Spacing } from '@/config/theme';

export default function ScannerScreen() { const [found, setFound] = useState(false); const router = useRouter(); return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Scanner QR Code</Text><Card style={styles.card}><View style={styles.scanner}><View style={styles.corner} /><Text style={styles.scanText}>{found ? 'Leitura simulada concluída' : 'Aponte para o QR Code do equipamento'}</Text></View></Card>{found ? <Card style={styles.card}><Text style={styles.section}>Equipamento encontrado</Text><Text style={styles.asset}>Compressor XPTO 500</Text><Text style={styles.muted}>Patrimônio: COMP-004</Text><Text style={styles.muted}>Local: Unidade Sorocaba</Text><Text style={styles.muted}>Status: Ativo</Text><Button label="Confirmar equipamento" onPress={() => router.push('/(protected)/inspections/ins-compressor')} fullWidth /><Button label="Escanear novamente" onPress={() => setFound(false)} variant="secondary" fullWidth /></Card> : <Button label="Simular leitura" onPress={() => setFound(true)} fullWidth size="lg" />}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, container: { padding: Spacing.md, gap: Spacing.md }, title: { fontSize: FontSize.xxl, color: Colors.text, fontWeight: FontWeight.bold }, card: { gap: Spacing.md }, scanner: { height: 320, borderRadius: 12, backgroundColor: Colors.text, alignItems: 'center', justifyContent: 'center' }, corner: { width: 190, height: 190, borderWidth: 3, borderColor: Colors.primaryLight, borderRadius: 20 }, scanText: { color: Colors.white, position: 'absolute', bottom: Spacing.lg, fontWeight: FontWeight.semibold }, section: { color: Colors.text, fontSize: FontSize.lg, fontWeight: FontWeight.semibold }, asset: { color: Colors.text, fontSize: FontSize.xl, fontWeight: FontWeight.bold }, muted: { color: Colors.textSecondary } });
