import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';

import { SeverityBadge } from '@/components/fieldops';
import { Button, Card } from '@/design-system';
import { Colors, FontSize, FontWeight, Spacing } from '@/config/theme';
import { compressorTemplate, Severity, useFieldOps } from '@/features/fieldops';

export default function NonConformitiesScreen() {
  const { id = 'ins-compressor' } = useLocalSearchParams<{ id: string }>(); const { nonConformities, addNonConformity } = useFieldOps(); const [open, setOpen] = useState(false); const [title, setTitle] = useState('Nova não conformidade'); const [description, setDescription] = useState('Descrição registrada em campo.'); const [severity, setSeverity] = useState<Severity>(Severity.MEDIUM); const [itemId, setItemId] = useState('item-4');
  const items = compressorTemplate.sections.flatMap((section) => section.items); const list = nonConformities.filter((nc) => nc.inspectionId === id);
  function save() { addNonConformity({ inspectionId: id, itemId, title, description, severity, evidenceCount: 0 }); setOpen(false); }
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Não conformidades</Text>{list.map((nc) => { const item = items.find((candidate) => candidate.id === nc.itemId); return <Card key={nc.id} style={styles.card}><View style={styles.row}><Text style={styles.ncTitle}>{nc.title}</Text><SeverityBadge severity={nc.severity} /></View><Text style={styles.muted}>Item: {item?.question}</Text><Text style={styles.muted}>Evidências: {nc.evidenceCount}</Text></Card>; })}<Button label="Nova não conformidade" onPress={() => setOpen(true)} fullWidth size="lg" /></ScrollView><Modal visible={open} transparent animationType="slide"><View style={styles.backdrop}><Card style={styles.modal}><Text style={styles.modalTitle}>Nova não conformidade</Text><TextInput value={title} onChangeText={setTitle} placeholder="Título" placeholderTextColor={Colors.gray400} style={styles.input} /><TextInput value={description} onChangeText={setDescription} placeholder="Descrição" placeholderTextColor={Colors.gray400} style={[styles.input, styles.textArea]} multiline /><Text style={styles.label}>Criticidade</Text><View style={styles.chips}>{Object.values(Severity).map((value) => <Pressable key={value} onPress={() => setSeverity(value)} style={[styles.chip, severity === value && styles.chipActive]}><Text style={[styles.chipText, severity === value && styles.chipTextActive]}>{value === Severity.LOW ? 'Leve' : value === Severity.MEDIUM ? 'Moderada' : value === Severity.HIGH ? 'Alta' : 'Crítica'}</Text></Pressable>)}</View><Text style={styles.label}>Item relacionado</Text><ScrollView style={styles.itemPicker}>{items.map((item) => <Pressable key={item.id} onPress={() => setItemId(item.id)} style={[styles.itemOption, itemId === item.id && styles.itemOptionActive]}><Text style={styles.muted}>{item.question}</Text></Pressable>)}</ScrollView><Button label="Salvar" onPress={save} fullWidth /><Button label="Cancelar" onPress={() => setOpen(false)} variant="ghost" fullWidth /></Card></View></Modal></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, container: { padding: Spacing.md, gap: Spacing.md, paddingBottom: Spacing.xxl }, title: { fontSize: FontSize.xxl, fontWeight: FontWeight.bold, color: Colors.text }, card: { gap: Spacing.sm }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm }, ncTitle: { flex: 1, color: Colors.text, fontSize: FontSize.md, fontWeight: FontWeight.semibold }, muted: { color: Colors.textSecondary, fontSize: FontSize.sm }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.30)' }, modal: { borderBottomLeftRadius: 0, borderBottomRightRadius: 0, gap: Spacing.md, maxHeight: '88%' }, modalTitle: { fontSize: FontSize.lg, color: Colors.text, fontWeight: FontWeight.bold }, input: { minHeight: 48, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, padding: Spacing.md, color: Colors.text, backgroundColor: Colors.surface }, textArea: { minHeight: 90, textAlignVertical: 'top' }, label: { color: Colors.textSecondary, fontWeight: FontWeight.semibold }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm }, chip: { minHeight: 40, borderRadius: 999, borderWidth: 1, borderColor: Colors.border, paddingHorizontal: Spacing.md, justifyContent: 'center' }, chipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary }, chipText: { color: Colors.textSecondary, fontWeight: FontWeight.semibold }, chipTextActive: { color: Colors.white }, itemPicker: { maxHeight: 160 }, itemOption: { padding: Spacing.sm, borderRadius: 8 }, itemOptionActive: { backgroundColor: Colors.primaryLight } });
