package br.com.fieldops.api.usuario.mapper;

import br.com.fieldops.api.usuario.model.Perfil;
import br.com.fieldops.api.usuario.model.Usuario;
import br.com.fieldops.api.usuario.dto.UsuarioResponse;
import org.mapstruct.Mapper;

/**
 * Maps between the {@link Usuario} entity and its {@link UsuarioResponse} DTO.
 * Generated by MapStruct at compile time.
 */
@Mapper(componentModel = "spring")
public interface UsuarioMapper {

    UsuarioResponse toResponse(Usuario usuario);

    UsuarioResponse toResponse(Long id, String nome, String email, Perfil perfil);
}
